
# 150 AMOSTRAS, DE 0 E 1, COM REPOSIÇÃO, PROB. EQUIVALENTES
```{r}

amostra <- sample(x = c(0,1),
                  size = 150,
                  replace = TRUE,
                  prob = c(0.5, 0.5))

amostra

summary(as.factor(amostra))

```

# 150 AMOSTRAS, DE 0 E 1, COM REPOSIÇÃO, + CHANCES PRO ZERO
```{r}

amostra <- sample(x = c(0,1),
                  size = 150,
                  replace = TRUE,
                  prob = c(0.8,0.2))

amostra


summary(as.factor(amostra))


```


#150 AMOSTRAS, DE 1 A 1000 SEM REPOSICAO E PROB. EQUIVALENTES
```{r}

amostra <- sample(x = c(1:1000),
                  size = 150,
                  replace = FALSE)

amostra

```



# PEGAR AMOSTRA ALEATORIA DE APROX. 30% DO CONJUNTO IRIS
```{r}

# GERO UM CONJUNTO ALEATORIO DE ZEROS E UN'S

amostra <- sample(x = c(0,1),
                  size =  nrow(iris),
                  replace = TRUE,
                  prob = c(0.7, 0.3))

summary(as.factor(amostra))




# PEGO NO IRIS SO ONDE EH 1

amostra_iris <- iris[amostra==1, ]

print("num linhas amostra_iris")
nrow(amostra_iris)



```

