x = EVENTOS
p = PROBABILIDADE
s = SIZE

SE JOGAR UMA MOEDA 5 VEZES, QUAL A CHANCE DE DAR CARA 3 VEZEZ?

```{r}


#OBS: dbinom ENCONTRA A CHANCE EXATA DE CAIR 3X, E NAO A ACUMULATIVA

dbinom(x = 3, size = 5, prob = 0.5)

```

SE PEGAR 4 SEMAFOROS DE 4 TEMPOS CADA, QUAL A CHANCE DE PEGAR 0,1,2,3 E 4 VERDES?

```{r}

#OBS: PBINOM FAZ A PROBABILIDADE ACUMULADA


sprintf("0 sinais: %f", pbinom(q = 0, size = 4, prob = 0.25)*100)
sprintf("1 sinais: %f", pbinom(q = 1, size = 4, prob = 0.25)*100)
sprintf("2 sinais: %f", pbinom(q = 2, size = 4, prob = 0.25)*100)
sprintf("3 sinais: %f", pbinom(q = 3, size = 4, prob = 0.25)*100)
sprintf("4 sinais: %f", pbinom(q = 4, size = 4, prob = 0.25)*100)


```

SE FIZER UMA PROVA DE 12 QUESTOES CHUTANDO TODAS, QUAL A CHANCE DE ACERTA 7?(4 ALTERNATIVAS POR QUESTAO)

```{r}

dbinom(x = 7, size = 12, prob = 0.25) * 100

```

SE PASSAR EM 4 SEMAFOROS DE 4 TEMPOS, QUAL A CHANCE DE PEGAR 3 OU MAIS SINAIS VERDES?
```{r}

1-pbinom(q = 2, size = 4, prob = 0.25)
pbinom(q = 2, size = 4, prob = 0.25, lower.tail = F)

#OU

dbinom(x = 3, size = 4, prob = 0.25) + dbinom(x = 4, size = 4, prob = 0.25)

```


