
# CARREGANDO A BASE
```{r}

base_tempo <- read.csv(file = "tempo.csv", 
                       header = TRUE, 
                       sep = ";",
                       na.strings = "")

head(x = base_tempo)

names(base_tempo)

```

# EXPLORACAO DOS DADOS
```{r}

bpk <- base_tempo

summary(base_tempo)

```

#TRATAMENTO E LIMPEZA DOS DADOS

```{r}

#=== APARENCIA ===#

bpk <- base_tempo

base_tempo$Aparencia

summary(base_tempo$Aparencia)


# TRANSFORMA EM FATOR
base_tempo$Aparencia <- factor(base_tempo$Aparencia)


# DOMINIOS ERRADOS TROCADOS PARA A MODA
base_tempo[!(base_tempo$Aparencia %in% c("chuva", "sol", "nublado")),'Aparencia'] <- "sol"

summary(base_tempo$Aparencia)


# REMOVENDO FATORES ZERADOS
base_tempo$Aparencia <- factor(base_tempo$Aparencia)
summary(base_tempo$Aparencia)

```



```{r}

#=== TEMPERATURA ===#

bpk <- base_tempo

summary(base_tempo$Temperatura)

boxplot(base_tempo$Temperatura)
boxplot(base_tempo$Temperatura, outline = FALSE)

valores_fdp <- boxplot(base_tempo$Temperatura)$out

# ATUALIZANDO OUTLINE PRA MEDIANA
base_tempo[base_tempo$Temperatura %in% valores_fdp,'Temperatura'] <- median(base_tempo$Temperatura, na.rm = TRUE)

```


```{r}

#=== UMIDADE ===#

bpk <- base_tempo

summary(base_tempo$Umidade)

boxplot(base_tempo$Umidade)

# VALORES N/A SUBSTITUIDOS PELA MEDIANA:
base_tempo[is.na(base_tempo$Umidade), 'Umidade'] <- median(x = base_tempo$Umidade, na.rm = TRUE)

# VALORES FORA DO INTERVALO SUBTUIDOS PELA MEDIANA
base_tempo[(base_tempo$Umidade<0 | base_tempo$Umidade>100), 'Umidade'] <- median(x = base_tempo$Umidade, na.rm = TRUE)

summary(base_tempo$Umidade)

boxplot(base_tempo$Umidade)

```

```{r}

# CAMPOS JOGAR E VENTO


# TRANSFORMANDO EM FATORES
base_tempo$Vento <- factor(base_tempo$Vento)
base_tempo$Jogar <- factor(base_tempo$Jogar)

summary(base_tempo$Vento) #PRECISA TRATAR OS NA
summary(base_tempo$Jogar) #NAO TEM O QUE TRATAR


base_tempo[is.na(base_tempo$Vento),'Vento'] <- "FALSO"


head(base_tempo)

```


