
# BLOXPLOT
```{r}

boxplot(trees$Volume,
        main = "Árvores",
        xlab = "Volume")


boxplot(trees$Volume,
        main = "Árvores",
        xlab = "Volume",
        #col = "blue",
        horizontal = TRUE)

boxplot(trees$Volume,
        main = "Árvores",
        xlab = "Volume",
        #col = "blue",
        horizontal = TRUE,
        outline = FALSE)


```



# INFORMACOES DO BOXPLOT
```{r}

boxplot.stats(trees$Volume)

boxplot.stats(trees$Volume)$stats

```


# BOXPLOT COM MAIS DE UMA VARIAVEL NUMERICA
```{r}

# EH SO CHAMAR COM UMA VARIAVEL QUE TENHA MAIS DE UMA COLUNA, TIPO UM DATA FRAME
boxplot(trees)

```


```{r}

InsectSprays

# SOMA TODAS AS VARIAVEIS DA COLUNA X, AGRUPANDO PELA COLUA Y
spray <- aggregate(. ~ spray, data = InsectSprays, sum)



# TESTANDO OUTRO MODO DE AGREGAR
testeAggregate <- aggregate(x = InsectSprays$count,
                            by = list(InsectSprays$spray),
                            FUN = sum)

spray
testeAggregate


names(testeAggregate) <- c("Spray", "Count")
testeAggregate


```

# GRAFICO DE BARRAS
```{r}

barplot(height = spray$count, 
        names.arg = spray$spray,
        xlab = "Spray",
        ylab = "Total",
        col = gray.colors(5))
box()

```

# GRAFICO DE PIZZA
```{r}

pie(x = spray$count)

pie(x = spray$count,
    labels = spray$spray)

pie(x = spray$count,
    labels = spray$spray,
    main = "Spray",
    col = c(1:6))

pie(x = spray$count,
    labels = NA,
    col = c(1:nrow(spray)))
legend(x = "bottomleft", legend = spray$spray, fill = c(1:nrow(spray)))



```

