

# HISTOGRAMA
```{r}

# BOM PRA ANALISAR UMA VARIAVEL NUMERICA CONTINUA DE CADA VEZ

df_arvores <- trees

head(df_arvores)

colnames(df_arvores) <- c("Circunferencia", "Altura", "Volume")

head(df_arvores)


# MOSTRA A FREQUENCIA DE DETERMINADO RANGE
hist(df_arvores$Altura)

hist(x = df_arvores$Altura, main = "Árvores")

hist(x = df_arvores$Altura, main = "Árvores", xlab = "Altura", ylab = "Frequência")

hist(x = df_arvores$Altura, main = "Árvores", xlab = "Altura", ylab = "Frequência",
     col = "blue", density = 20, breaks = 20)

```


# GERANDO O GRAFICO ACIMA ATRAVES DE DENSIDADE
```{r}

densidade <- density(df_arvores$Altura)

plot(x = densidade)

```

# DENSIDADE SOB O HISTOGRAMA
```{r}

hist(x = df_arvores$Altura, main = NULL, xlab = NULL, ylab = NULL)

# INFORMO QUE A PROX INSTRUCAO DEVE SER SOBREPOSTA NO GRAFICO DA INSTRUCAO ANTERIOR
par(new = TRUE)

plot(densidade, main = "Árvores", xlab = "Altura")


```


# GRAFICO DE DISPERSAO
```{r}

# UTILIZADO PRA COMPARAR VARIAVEIS CONTINUAS

plot(x = df_arvores$Circunferencia, y = df_arvores$Volume)


plot(x = df_arvores$Circunferencia, y = df_arvores$Volume,
     main = "Árvores",
     xlab = "Circunferencia", ylab = "Volume",
     col = "blue")


#PCH = MUDA O ELEMENTO GRAFICO

plot(x = df_arvores$Circunferencia, y = df_arvores$Volume,
     main = "Árvores",
     xlab = "Circunferencia", ylab = "Volume",
     col = "blue",
     pch = 20)

```


# MUDANDO O GRAFICO 
```{r}

plot(x = df_arvores$Circunferencia, y = df_arvores$Volume,
     main = "Árvores",
     xlab = "Circunferencia", ylab = "Volume",
     col = "blue",
     pch = 20,
     type = "l")

```

