
# IMPORTACAO ARQUIVO

```{r}


setwd("D:\\Documentos\\Cursos\\FormacaoCD")


# STRING VAZIO COMO N/A E STRING COMO FATOR

dados <- read.csv(file = "Churn.csv", sep = ";", na.strings = "", stringsAsFactors = T)

head(dados)

summary(dados)


```


# DAR NOMES PARA AS COLUNAS

```{r}

nomesColunas <- c("Id", "Score", "Estado", "Genero", "Idade", "Patrimonio", 
                  "Saldo", "Produtos", "TemCartaoCredito", "Ativo", "Salario", "Saiu")

colnames(dados) <- nomesColunas


head(dados)


```



# EXPLORAR DADOS - COLUNAS CATEGORICAS

```{r}

# ESTADOS
#table(dados$Estado) #cria uma tabela, contabiliza quantas repeticoes tem pra cada item

contagemEstados <- table(dados$Estado)

#BARPLOT: PLOT DE BARRAS?
barplot(contagemEstados, main = "Estados")



#=== GENERO ===#
count_genero <- table(dados$Genero)

barplot(count_genero, main = "Genero")


```

# EXPLORACAO DADOS NUMERICOS

```{r}

# SCORE

summary(dados$Score)

boxplot(dados$Score)

hist(dados$Score, xlab = "Score", main = "Score clientes")

```


```{r}

# IDADE

summary(dados$Idade)

boxplot(dados$Idade)

hist(dados$Idade)

```



```{r}

# SALDO

summary(dados$Saldo)

boxplot(dados$Saldo)

hist(dados$Saldo)

```


```{r}

# SALARIO

summary(dados$Salario)

boxplot(dados$Salario)

hist(dados$Salario)

```


# VALORES FALTANTES N/A
```{r}


# FUNCAO COMPLETE.CASE SELECIONA OS DADOS QUE ESTAO PREENCHIDOS

# PEGANDO OS VALORES FALTANTES]
dados[!complete.cases(dados), ]


```


# SALARIOS
```{r}

bkp <- dados

# TRATAR SALARIOS
summary(dados$Salario)

# CALCULO DA MEDIANA DOS SALARIOS
mediana_salarios <- median(x = dados$Salario, na.rm = TRUE)

# ATRIBUIR VALOR DA MEDIANA AOS VALORES NA
dados[is.na(dados$Salario),]$Salario <- mediana_salarios
#ou
dados[is.na(x = dados$Salario),'Salario'] <- mediana_salarios


dados[!complete.cases(dados$Salario), ]



```



# FALTA DE PADROZINACAO NO GENERO

```{r}


# ver os dados (tipo um selec distinct)

#unique(dados$Genero)
#summary(dados$Genero)


dados[dados$Genero == "M" | is.na(dados$Genero), 'Genero'] <- "Masculino"
dados[dados$Genero == "F" | dados$Genero == "Fem", 'Genero'] <- "Feminino"

summary(dados$Genero)
#summary(bkp$Genero)

# REMOVER FATORES ZERADOS/NAO UTILIZADOS
dados$Genero <- factor(dados$Genero)

summary(dados$Genero)

```


# IDADES FORA DO DOMINIOS


```{r}

bkp <- dados

# VER AS IDADES FORA DO DOMINIO
dados[dados$Idade<0 | dados$Idade>110,]

#ASSUMIR VALOR DA MEDIANA PAPARA ESTAS IDADES
dados[dados$Idade<0 | dados$Idade>110,'Idade'] <- median(x = dados$Idade)

# VER SE AINDA TEM IDADES FORA DO DOMINIO
dados[dados$Idade<0 | dados$Idade>110,]

summary(dados$Idade)

```


# DADOS DUPLICADOS

```{r}

bkp <- dados

# BUSCANDO SE TEM DADOS DUPLICADOS
dados[duplicated(dados$Id), ]


#REMOVENDO AS LINHAS QUE ESTAO DUPLICADAS
dados <- dados[-c(82),]

#ou

dados <- dados[!duplicated(dados$Id), ]

dados[duplicated(dados$Id), ]


```

# ESTADOS QUE NÃO EXISTEM / FORA DO DOMINIO

```{r}

bkp <- dados
dados <- bkp

summary(dados$Estado)

head(dados)

dados[!(dados$Estado %in% c('RS', 'SC', 'PR')),'Estado'] <- "RS"


# REMOVER FATORES ZERADOS
dados$Estado <- factor(dados$Estado)


```



