
# DATAFRAME CARS: MOSTRA VELOCIDADE E TEMPO DE PARAGEM DOS CARROS
```{r}

#install.packages("corrgram")
library(corrgram)

cars

```


# CALCULO CORRELACAO ENTRE AS VARIAVEIS VELOCIDADE X TEMPO PARAGEM
```{r}

cor(x= cars)

corrgram(x = cars,
         order = T,
         lower.panel = panel.shade,
         upper.panel = panel.pie,
         text.panel = panel.txt,
         main = "Carros")

```


# CRIACAO DO MODELO USANDO A FUNCAO lm()

```{r}

# MODELO PRA PREVER VELOCIDADE EM FUNCAO / A PARTIR DA DISTANCIA

modelo <- lm(data = cars,
             formula = cars$speed ~ cars$dist)

modelo

```

# VISUALIZACAO DA RELACAO ENTRE AS VARIAVEIS E A LINHA DE MELHOR AJUSTE
```{r}

plot(cars$speed ~ cars$dist,
     data = cars,
     xlab = "Distancia",
     ylab = "Velocidade",
     main = "Carros")

abline(modelo, col = "red")

?abline

```


# PREVISAO USANDO O MODELO CRIADO
```{r}

predict(object = modelo,
        newdata = data.frame(dist = 22))

```


# ANALISANDO MELHOR O MODELO
```{r}

options(scipen=666)

summary(modelo)

modelo$coefficients

shapiro.test(modelo$residuals)

hist(modelo$residuals)


qqnorm(modelo$residuals)
qqline(modelo$residuals, col = "red")



```


